const permits = [
  "(TEST ONLY) Testing Advanced Table Controls",
  "2B_Deleted_ANC Treatment Report (Great Lakes Invasives)",
  "Address Default Test",
  "Address Test ",
  "Application For Bottomland Conveyance (Part-325)",
  "Application for Certificate of Coverage (COC) to Chemically Control Nuisance Aquatic Plants and Algae",
  "Application For Conveyance For Offshore Lighthouse (Part-325)",
  "Application for Permit to Chemically Control Nuisance Aquatic Plants and Algae",
  "Application For Permit To Recover Abandoned Property From The Great Lakes (Part 761)",
  "Application for Wetland Restoration Permit",
  "Application Under County Drains General Permit Category",
  "Asbestos - Project Application - New TESTING",
  "Certification Test",
  "Department Initiated Permit Action Form (NPDES) - DIA (Internal)",
  "Department Initiated Permit Action Form (Solid Waste) - DIA (Internal)",
  "Dummy Test Form Imported On 10/2/2018 16:21:20",
  "Electronic Sig Test From",
  "Feature Prepop Test Form",
  "Form To Test Site Component Inheritance",
  "Gerald Feature ID Test",
  "Gerald Feature Prepop Test Form",
  "Gerald Feature Prepop Test Form 3",
  "Gerald Feature Prepop Test Form 4",
  "Gerald Test Form 100",
  "Gerald Test Form 101",
  "Gerald's test form",
  "Groundwater Discharge Permit Application Discharge Permits Rule 323.2218",
  "Groundwater Discharge Permit Application General Permit: Rule 323.2215",
  "Groundwater Discharge Permit Application Permit By Rule Notification With Department Certification: Rule 323.2213",
  "Groundwater Discharge Permit Application Permit By Rule Notification: Rule 323.2211",
  "Groundwater Discharge Permit Application Permits For Specific Discharges: Rule 323.2216",
  "Groundwater Discharge Permit Application Site Specific Authorization: Rule 323.2210(y)",
  "Groundwater General Permit - 2215-10-8 - Hydrostatic Test Water - Notice of Intent (NOI)",
  "Jami's 4.4 test form",
  "Jami's DI Donor form",
  "John Test Form",
  'LARGE CAFO  “NO POTENTIAL TO DISCHARGE" DETERMINATION REQUEST',
  "MDEQ/USACE Joint Permit Application (JPA) for Inland Lakes and Streams, Great Lakes, Wetlands, Floodplains, Dams, Environmental Areas, High Risk Erosion Areas and Critical Dune Areas",
  "MIWDEV-10197",
  "National Pollutant Discharge Elimination System (NPDES) Concentrated Animal Feed Operation Application Form (CAFO)",
  "National Pollutant Discharge Elimination System (NPDES) Municipal Application Form",
  "National Pollutant Discharge Elimination System (NPDES) Municipal Separate Storm Sewer System (MS4) Application Form",
  "New Form for Contacts",
  "No Exposure Certification (NEC) for Exclusion of Coverage under the NPDES Storm Water Discharges Associated with Industrial Activity",
  "No Potential To Discharge For Exclusion Of Coverage Under The National Pollutant Discharge Elimination System (NPDES) Storm Water Discharges Associated With Construction Activity",
  "Notice of Coverage (NOC) for NPDES Storm Water Discharges from Construction Activity",
  "Notice Of Intent (NOI) For Coverage Under The National Pollutant Discharge Elimination System (NPDES) For Storm Water Discharges Associated With Industrial Activity",
  "Notice Of Intent (NOI) For Coverage Under The National Pollutant Discharge Elimination System (NPDES) For Storm Water Discharges Associated With Industrial Activity And Certificate Of Entry (COE)",
  "Notice of Proposed Underground Storage Tank (UST) System New Installation",
  "NPDES Point Source Discharge Permit Application - Pesticide Discharges",
  "Permit Application for Port Operations and Ballast Water Discharges",
  "Pre-Application Meeting Request  Part 353 (Critical Dune Area)",
  "Pre-Payment Test Form",
  "Public Transportation Projects MDEQ/USACE Joint Permit Application (JPA) for Inland Lakes and Streams, Great Lakes, Wetlands, Floodplains, Dams, Environmental Areas, High Risk Erosion Areas and Critical Dune Areas",
  "Recreational dredging dewatering water discharges - Notice of Intent (NOI)",
  "SIC Code Integration Test (NCORE-3668)",
  "Simple Test Form",
  "Site and Contacts Form",
  "Social Security Number Control Test Form",
  "Stormwater Notice of Intent (NOI) - Construction Activities (D 2617)",
  "Test Application to populate Person Details with Contact Control and multiple phone numbers",
  "Test Bottom App",
  "Test Calc Form",
  "Test Fee Calc Form",
  "TEST FORM Emily Template Test",
  "Test Form For JPA Fees3213",
  "Test Form: nForm 4.7 Document Upload",
  "Test Site A - Site Name and Address with County",
  "TEST Waterbody",
  "Transportation Emergency Request Form",
  "Windsor Test form- 4.9 Single Sig 1",
  "Windsor Test nForm 4.9 - Mult Elec Sig (Groundwater)",
  "Windsor Test nForm 4.9 - Mult Elec Sig (Resources)",
];

export default permits;
